version: '3'

services:
  auth_ms:
    build: .
    command: flask run --host=0.0.0.0
    #command: python manage.py runserver 0.0.0.0:8000 0:8000
    volumes:
      - .:/code
    ports:
      - "5002:5000"
